AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
    HelloWorldFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: dist/functions/hello_world/
            Handler: handler
            Runtime: go1.x
            Events:
                CatchAll:
                    Type: Api
                    Properties:
                        Path: /hello/{name}
                        Method: GET
                        RestApiId: !Ref ShortenerApi
            Environment:
                Variables:
                    NAME_PREFIX: IP adress

    CreateUrlFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: create_url
            CodeUri: dist/functions/create_url/
            Handler: handler
            Runtime: go1.x
            Events:
                Post:
                    Type: Api
                    Properties:
                        Path: /short
                        Method: post
                        RestApiId: !Ref ShortenerApi
            Environment:
                Variables:
                    TABLE_NAME: !Ref DynamoDBTable
            Policies:
                - DynamoDBCrudPolicy:
                      TableName: !Ref DynamoDBTable

    DynamoDBTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: short-ids
            BillingMode: PAY_PER_REQUEST
            KeySchema:
                - AttributeName: short_id
                  KeyType: HASH
            AttributeDefinitions:
                - AttributeName: short_id
                  AttributeType: S
            StreamSpecification:
                StreamViewType: NEW_IMAGE

    GetUrlFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: get_url
            CodeUri: dist/functions/get_url/
            Handler: handler
            Runtime: go1.x
            Events:
                Get:
                    Type: Api
                    Properties:
                        Path: /short/{short_id}
                        Method: get
                        RestApiId: !Ref ShortenerApi
            Environment:
                Variables:
                    TABLE_NAME: !Ref DynamoDBTable
            Policies:
                - DynamoDBReadPolicy:
                      TableName: !Ref DynamoDBTable

    ShortenerApi:
        Type: AWS::Serverless::Api
        Properties:
            EndpointConfiguration: REGIONAL
            StageName: Prod
            Cors:
                AllowMethods: "'POST,OPTIONS'"
                AllowHeaders: "'content-type'"
                AllowOrigin: "'*'"

    PreviewFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: preview
            CodeUri: dist/functions/preview/
            Handler: handler
            Runtime: go1.x
            Events:
                DynamoDBEvent:
                    Type: DynamoDB
                    Properties:
                        Stream:
                          !GetAtt DynamoDBTable.StreamArn
                        StartingPosition: TRIM_HORIZON
                        BatchSize: 10
            Environment:
                Variables:
                    TABLE_NAME: !Ref PreviewTable
            Policies:
                - DynamoDBCrudPolicy:
                      TableName: !Ref PreviewTable

    PreviewTable:
        Type: AWS::Serverless::SimpleTable
        Properties:
            TableName: url-shortener-preview
            PrimaryKey:
                Name: url
                Type: String

Outputs:
    HelloWorldEndpoint:
        Description: "Hello World function HTTPS endpoint"
        Value: !Sub "https://${ShortenerApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello"
    ShortURLEndpoint:
        Description: "Short URL functions HTTPS endpoint"
        Value: !Sub "https://${ShortenerApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/short"
