AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
    HelloWorldFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: dist/functions/hello_world/
            Handler: handler
            Runtime: go1.x
            Events:
                CatchAll:
                    Type: Api
                    Properties:
                        Path: /hello/{name}
                        Method: GET
            Environment:
                Variables:
                    NAME_PREFIX: IP adress

Outputs:
    HelloWorldEndpoint:
        Description: "Hello World function HTTPS endpoint"
        Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello"
