AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
    HelloWorldFunction:
        Type: AWS::Serverless::Function
        Properties:
            Tracing: Active
            CodeUri: dist/functions/hello_world/
            Handler: handler
            Runtime: go1.x
            Events:
                CatchAll:
                    Type: Api
                    Properties:
                        Path: /hello/{name}
                        Method: GET
                        RestApiId: !Ref ShortenerApi
            Environment:
                Variables:
                    NAME_PREFIX: IP adress
            AutoPublishAlias: live
            DeploymentPreference:
                Type: Canary10Percent5Minutes
                Alarms:
                    - !Ref AliasErrorMetricGreaterThanZeroAlarm
                    - !Ref LatestVersionErrorMetricGreaterThanZeroAlarm

    CreateUrlFunction:
        Type: AWS::Serverless::Function
        Properties:
            Tracing: Active
            FunctionName: create_url
            CodeUri: dist/functions/create_url/
            Handler: handler
            Runtime: go1.x
            Events:
                Post:
                    Type: Api
                    Properties:
                        Path: /short
                        Method: post
                        RestApiId: !Ref ShortenerApi
                        Auth:
                            Authorizer: CognitoAuthorizer
            Environment:
                Variables:
                    TABLE_NAME: !Ref DynamoDBTable
            Policies:
                - DynamoDBCrudPolicy:
                      TableName: !Ref DynamoDBTable

    DynamoDBTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: short-ids
            BillingMode: PAY_PER_REQUEST
            KeySchema:
                - AttributeName: short_id
                  KeyType: HASH
            AttributeDefinitions:
                - AttributeName: short_id
                  AttributeType: S
            StreamSpecification:
                StreamViewType: NEW_IMAGE

    GetUrlFunction:
        Type: AWS::Serverless::Function
        Properties:
            Tracing: Active
            FunctionName: get_url
            CodeUri: dist/functions/get_url/
            Handler: handler
            Runtime: go1.x
            Events:
                Get:
                    Type: Api
                    Properties:
                        Path: /short/{short_id}
                        Method: get
                        RestApiId: !Ref ShortenerApi
            Environment:
                Variables:
                    TABLE_NAME: !Ref DynamoDBTable
            Policies:
                - DynamoDBReadPolicy:
                      TableName: !Ref DynamoDBTable
            ReservedConcurrentExecutions: 1

    GetUrlFunctionErrorsAlarm:
        Type: AWS::CloudWatch::Alarm
        Properties:
            AlarmActions:
                - !Ref AlarmTopic # send a message to this SNS topic
            AlarmDescription: Number of errors of GetUrl function is too high
            ComparisonOperator: GreaterThanThreshold
            DatapointsToAlarm: 2 # Two data points must be "GreaterThanThreshold"
            EvaluationPeriods: 5 # out of five data points
            Dimensions:
                - Name: FunctionName
                  Value: !Ref GetUrlFunction
            MetricName: Errors
            Namespace: AWS/Lambda
            OKActions:
                - !Ref AlarmTopic # send a message to this SNS topic
            Period: 60 # check every 60 seconds
            Statistic: Sum
            Threshold: 3
            TreatMissingData: ignore

    GetUrlFunctionThrottledAlarm:
        Type: AWS::CloudWatch::Alarm
        Properties:
            AlarmActions:
                - !Ref AlarmTopic # send a message to this SNS topic
            AlarmDescription: GetUrl function is beeing throttled
            ComparisonOperator: GreaterThanThreshold
            DatapointsToAlarm: 1 # As soon one throttling happens, the alarm triggers
            Dimensions:
                - Name: FunctionName
                  Value: !Ref GetUrlFunction
            EvaluationPeriods: 1
            MetricName: Throttles
            Namespace: AWS/Lambda
            OKActions:
                - !Ref AlarmTopic # send a message to this SNS topic
            Period: 60 # check every 60 seconds
            Statistic: Sum
            Threshold: 1
            TreatMissingData: ignore

    AlarmTopic:
        Type: AWS::SNS::Topic

    ShortenerApi:
        Type: AWS::Serverless::Api
        Properties:
            TracingEnabled: true
            EndpointConfiguration: REGIONAL
            StageName: Prod
            Cors:
                AllowMethods: "'POST,OPTIONS'"
                AllowHeaders: "'content-type, authorization'"
                AllowOrigin: "'*'"
            Auth:
                Authorizers:
                    CognitoAuthorizer:
                        UserPoolArn: !GetAtt UserPool.Arn

    PreviewFunction:
        Type: AWS::Serverless::Function
        Properties:
            Tracing: Active
            FunctionName: preview
            CodeUri: dist/functions/preview/
            Handler: handler
            Runtime: go1.x
            Events:
                DynamoDBEvent:
                    Type: DynamoDB
                    Properties:
                        Stream:
                          !GetAtt DynamoDBTable.StreamArn
                        StartingPosition: TRIM_HORIZON
                        BatchSize: 10
            Environment:
                Variables:
                    TABLE_NAME: !Ref PreviewTable
            Policies:
                - DynamoDBCrudPolicy:
                      TableName: !Ref PreviewTable

    PreviewTable:
        Type: AWS::Serverless::SimpleTable
        Properties:
            TableName: url-shortener-preview
            PrimaryKey:
                Name: url
                Type: String

    UserPool:
        Type: AWS::Cognito::UserPool
        Properties:
            AutoVerifiedAttributes:
                - email
            EmailVerificationSubject: 'Your verification code'
            EmailVerificationMessage: 'Your code is {####}'
            UserPoolName: ShortenerUsers
            Policies:
                PasswordPolicy:
                    MinimumLength: 8
            UsernameAttributes:
                - email
            Schema:
                - AttributeDataType: String
                  Name: email
                  Required: false

    UserPoolClient:
        Type: AWS::Cognito::UserPoolClient
        Properties:
            UserPoolId: !Ref UserPool
            ClientName: ShortenerUsersClient
            GenerateSecret: false

    AliasErrorMetricGreaterThanZeroAlarm:
        Type: "AWS::CloudWatch::Alarm"
        Properties:
            AlarmDescription: Lambda Function Error > 0
            ComparisonOperator: GreaterThanThreshold
            Dimensions:
                - Name: Resource
                  Value: !Sub "${HelloWorldFunction}:live"
                - Name: FunctionName
                  Value: !Ref HelloWorldFunction
            EvaluationPeriods: 2
            MetricName: Errors
            Namespace: AWS/Lambda
            Period: 60
            Statistic: Sum
            Threshold: 0
            TreatMissingData: ignore

    LatestVersionErrorMetricGreaterThanZeroAlarm:
        Type: "AWS::CloudWatch::Alarm"
        Properties:
            AlarmDescription: Lambda Function Error > 0
            ComparisonOperator: GreaterThanThreshold
            Dimensions:
                - Name: Resource
                  Value: !Sub "${HelloWorldFunction}:live"
                - Name: FunctionName
                  Value: !Ref HelloWorldFunction
                - Name: ExecutedVersion
                  Value: !GetAtt HelloWorldFunction.Version.Version
            EvaluationPeriods: 2
            MetricName: Errors
            Namespace: AWS/Lambda
            Period: 60
            Statistic: Sum
            Threshold: 0
            TreatMissingData: ignore

Outputs:
    HelloWorldEndpoint:
        Description: "Hello World function HTTPS endpoint"
        Value: !Sub "https://${ShortenerApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello"
    ShortURLEndpoint:
        Description: "Short URL functions HTTPS endpoint"
        Value: !Sub "https://${ShortenerApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/short"
    UserPoolId:
        Description: "Id of the Cognito User Pool to be referenced in Clients"
        Value: !Ref UserPool
    UserPoolClientId:
        Description: "Id of the Cognito User Pool Client"
        Value: !Ref UserPoolClient
